#!/bin/bash

# Script to rewrite git history and change author/committer from Claude to ReserveBTC
# This will clean up the commit history to show proper ReserveBTC authorship

echo "🔄 Rewriting Git History - Changing authorship from Claude to ReserveBTC"
echo "============================================================"

# Backup current branch
echo "📋 Creating backup branch..."
git branch backup-before-rewrite

# Set new author information
export FILTER_BRANCH_SQUELCH_WARNING=1
NEW_NAME="ReserveBTC"
NEW_EMAIL="dev@reservebtc.io"

echo "🔧 New author info:"
echo "   Name: $NEW_NAME"
echo "   Email: $NEW_EMAIL"

# Rewrite git history to change author and committer
echo "🔄 Rewriting commit history..."
git filter-branch --env-filter "
    if [ \$GIT_COMMITTER_EMAIL = 'noreply@anthropic.com' ] || [ \$GIT_AUTHOR_EMAIL = 'noreply@anthropic.com' ]
    then
        export GIT_COMMITTER_NAME='$NEW_NAME'
        export GIT_COMMITTER_EMAIL='$NEW_EMAIL'
        export GIT_AUTHOR_NAME='$NEW_NAME'
        export GIT_AUTHOR_EMAIL='$NEW_EMAIL'
    fi
" --tag-name-filter cat -- --branches --tags

# Also rewrite any commits that might have Claude references
echo "🧹 Cleaning up any remaining Claude references..."
git filter-branch -f --msg-filter "
    sed 's/Generated with \[Claude Code\]/Generated by ReserveBTC Team/g' |
    sed 's/Co-Authored-By: Claude <noreply@anthropic.com>/Co-Authored-By: ReserveBTC Team <dev@reservebtc.io>/g' |
    sed 's/🤖 Generated with Claude Code/🚀 Built by ReserveBTC Team/g'
" -- --branches --tags

# Clean up backup refs
echo "🧹 Cleaning up backup references..."
git for-each-ref --format="%(refname)" refs/original/ | xargs -n 1 git update-ref -d

# Force garbage collection
echo "🗑️  Running garbage collection..."
git gc --aggressive --prune=now

# Update git config for future commits
echo "⚙️  Updating git config for future commits..."
git config user.name "ReserveBTC"
git config user.email "dev@reservebtc.io"

# Show the result
echo ""
echo "✅ Git history rewrite completed!"
echo "============================================================"
echo "📊 Recent commits now show:"
git log --oneline -5 --pretty=format:"%h %an <%ae> %s" HEAD

echo ""
echo ""
echo "🎯 Summary of changes:"
echo "   ✅ All commits now authored by: ReserveBTC <dev@reservebtc.io>"
echo "   ✅ Commit messages cleaned of Claude references"
echo "   ✅ Git config updated for future commits"
echo "   ✅ Backup created at: backup-before-rewrite branch"
echo ""
echo "🚨 WARNING: This rewrites git history!"
echo "   - All commit hashes have changed"
echo "   - You'll need to force push: git push origin main --force-with-lease"
echo "   - Other collaborators will need to reset their local branches"
echo ""
echo "🔄 Ready to push rewritten history to GitHub?"
echo "   Run: git push origin main --force-with-lease"
echo ""
echo "📋 If you need to restore original history:"
echo "   Run: git reset --hard backup-before-rewrite"