name: Foundry Tests
on:
  push:
    branches: [ main, develop ]
    paths:
      - 'contracts/**'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  foundry-ci:
    name: Foundry CI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1
      with:
        version: nightly
    - name: Run tests
      run: |
        cd contracts
        forge test --verbosity 2
    - name: Generate gas report
      run: |
        cd contracts
        forge test --gas-report > gas-report.txt
        cat gas-report.txt