# .github/workflows/bip322-public-verification.yml
name: BIP-322 Public Verification (Anyone Can Run)

on:
  workflow_dispatch: 
  push:
    branches: [ main ]
    paths:
      - 'scripts/security-audit-bip322-ci.js'
      - 'backend/bitcoin-provider/**'
  
jobs:
  public-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run BIP-322 security tests
        run: node scripts/security-audit-bip322-ci.js
      
      - name: Publish test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: bip322-test-results
          path: |
            test-results/
            *.log
          retention-days: 30