name: Bitcoin Provider Tests
on:
  push:
    branches: [ main, develop ]
    paths:
      - 'backend/bitcoin-provider/**'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

# Integration tests require Bitcoin RPC server (regtest:18443) which is not available in GitHub Actions
# Only unit tests are executed to verify core functionality

jobs:
  all-unit-tests:
    name: All Bitcoin Provider Unit Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    - name: Install dependencies
      run: |
        cd backend/bitcoin-provider
        npm ci
    - name: Run all unit tests (skip integration)
      run: |
        cd backend/bitcoin-provider
        npx vitest run test/unit/ --reporter=verbose

  bip322-verification:
    name: BIP-322 Signature Verification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    - name: Install dependencies
      run: |
        cd backend/bitcoin-provider
        npm ci
    - name: Test BIP-322 signature verification module
      run: |
        cd backend/bitcoin-provider
        npx vitest run test/unit/bip322-verify.unit.test.ts --reporter=verbose

  bitcoin-indexer-tests:
    name: Bitcoin Indexer Unit Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    - name: Install dependencies
      run: |
        cd backend/bitcoin-provider
        npm ci
    - name: Test bitcoin indexer functionality
      run: |
        cd backend/bitcoin-provider
        npx vitest run test/unit/bitcoin-indexer.unit.test.ts --reporter=verbose
        npx vitest run test/unit/bitcoin-indexer.edges.unit.test.ts --reporter=verbose

  selfsend-detector-tests:
    name: Self-Send Detector Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    - name: Install dependencies
      run: |
        cd backend/bitcoin-provider
        npm ci
    - name: Test self-send detector functionality
      run: |
        cd backend/bitcoin-provider
        npx vitest run test/unit/selfsend-detector.unit.test.ts --reporter=verbose

