name: Smart Contract Test Suite
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  FOUNDRY_DISABLE_NIGHTLY_WARNING: true

jobs:
  all-contract-tests:
    name: All Smart Contract Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1
      with:
        version: nightly
    - name: Run all Foundry tests
      run: |
        cd contracts
        forge test --verbosity 1

  gas-report:
    name: Gas Usage Report
    runs-on: ubuntu-latest
    needs: [all-contract-tests]
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1
      with:
        version: nightly
    - name: Generate gas snapshots
      run: |
        cd contracts
        forge test --gas-report > gas-report.txt
        cat gas-report.txt